/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 model.glb 
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/2021-lamborghini-countach-lpi-800-4-d76b94884432422b966d1a7f8815afb5
Title: 2021 Lamborghini Countach LPI 800-4
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
export function Model(props) {
  const { nodes, materials } = useGLTF("../../../models/car/model.glb");
  const modelref = useRef(null);
  // useEffect(() => {
  //   if(modelref.current)
  //   console.log(modelref.current);
  // }, []);

  return (
    <group {...props} ref={modelref} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          // material={materials["Material.001"]}
        />
        <lineSegments
          geometry={nodes.Object_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.010"]}
        />
        <lineSegments
          geometry={nodes.Object_6.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Material.042"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Lamborghini-text-logo-1440x900"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Material.002"]}
        />
        <lineSegments
          geometry={nodes.Object_15.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials["Material.029"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../models/car/model.glb");
